### ISSUE TITLE
Can't install because `gradient` has been removed

### ISSUE THREAD

**Issue by moigagoo** [Knaque/spinner#1]
Spinner depends on gradient and gradient repo has been removed from GitHub.

**Comment by possdog** [comment]
Spinner is an old project that was poor in conception and poor in execution. I have no plans to maintain the project, but I *may* remake it from scratch with a better design philosophy when Fidget2 is released.

Feel free to fork it and make whatever changes you need, but good luck working with code that makes me cringe just thinking about it.

(Yes, I know, I should archive this repo.)
